# The URL the site will be built for
base_url = "https://rustlang.cz"

title = "Homepage of the Czech Rust community"
description = "This site serves as an index for information about the Rust language community based in the Czech Republic."
author = "Jakub Ber√°nek"
default_language = "en"

compile_sass = true
minify_html = true
build_search_index = false

generate_feed = true
feed_limit = 50

[markdown]
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
github_url = "https://github.com/kobzol/rustlang.cz"
